# Generated by Django 5.1.6 on 2025-03-04 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_level', models.CharField(choices=[('server', 'Server'), ('project', 'Project'), ('group', 'Group')], max_length=10)),
                ('target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('target_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hooks.hook')),
                ('hook_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hooks.hookversion')),
            ],
            options={
                'ordering': ['-deployed_at'],
            },
        ),
    ]
